const BuildingType = {
    SINGLE_FAMILY_HOUSE: 'SINGLE_FAMILY_HOUSE',
    TWO_FAMILY_HOUSE: 'TWO_FAMILY_HOUSE',
    MULTI_FAMILY_HOUSE: 'MULTI_FAMILY_HOUSE',
    APARTMENT_BUILDING: 'APARTMENT_BUILDING',
    TENEMENT: 'TENEMENT',
    SKYSCRAPER: 'SKYSCRAPER',
    HALL: 'HALL',
    WAREHOUSE: 'WAREHOUSE'
};

export default BuildingType;

