
const Standard = {
    DEVELOPER_STANDARD: 'DEVELOPER_STANDARD',
    FINISHED_STANDARD: 'FINISHED_STANDARD',
    FOR_RENOVATION: 'FOR_RENOVATION',
    GOOD_STANDARD: 'GOOD_STANDARD',
    HIGH_STANDARD: 'HIGH_STANDARD',
};

export default Standard;