const TypeOfBusiness = {
	GASTRONOMY: "GASTRONOMY",
	COSMETOLOGY: "COSMETOLOGY",
	SHOP: "SHOP",
	SUPERMARKET: "SUPERMARKET",
	SERVICES: "SERVICES",
	OFFICE: "OFFICE",
	OTHER: "OTHER",
};

export default TypeOfBusiness;
